### PR TITLE
Fix TypeScript 3.5 compatibility

### LINKED ISSUE #66: [TypeScript] Index signature is missing in type 'DefaultAddOptions'
Since upgrading `typescript@3.5.1` I get this compile error:
```
node_modules/p-queue/index.d.ts:81:54 - error TS2344: Type 'DefaultAddOptions' does not satisfy the constraint 'QueueAddOptions'.
  Index signature is missing in type 'DefaultAddOptions'.

81  EnqueueOptionsType extends PQueue.QueueAddOptions = PQueue.DefaultAddOptions
                                                        ~~~~~~~~~~~~~~~~~~~~~~~~
```
My `tsconfig.json` looks like:
```json
{
	"compilerOptions": {
		"lib": ["esnext"],
		"module": "commonjs",
		"target": "es5"
	}
}
```

### PR DESCRIPTION
**Pull request by JustinBeckwith**
This fixes #66.  In our TypeScript npm modules, we're unable to use this library because of the bug in #66.  This PR does a few things:
- Bumps the required TypeScript version to `3.5.1`
- Moves to a `~` range specifier, as the TypeScript compiler makes breaking changes in minor relases
- Loosens the type required for `DefaultAddOptions`.  I'm not super confident with this particular change, so it could use another set of 👀

### CODE REVIEW

File: source/options.ts [hunk 1]
```diff
@@ -71,4 +71,6 @@ export interface DefaultAddOptions {
 	@default 0
 	*/
 	readonly priority?: number;
+
+	readonly [key: string]: unknown;
```
Comment (callmehiphop) [inline source/options.ts]: Not sure if this is the right way to go, buuut if the idea is to satisfy `QueueAddOptions`, it might be better to just extend it?

Comment (JustinBeckwith) [reply source/options.ts]: Good call 👍
