### PR TITLE
Reject on sync function error

### LINKED ISSUE #32: Sync function error breaks everything
What if [`fn()`](https://github.com/sindresorhus/p-queue/blob/master/index.js#L96) fails? Example:

```javascript
(async function() {
	let queue = new PQueue({ concurrency: 1 });
	
	queue.add(() => { throw 'x' }).catch(console.log);
	queue.add(() => { throw 'y' }).catch(console.log);
})();
```

### PR DESCRIPTION
**Pull request by szmarczak**
Fixes #32 

Because we accept synchronous functions, they may throw an error. So `p-queue` crashes because there's nothing to handle that error.

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -93,7 +93,7 @@ class PQueue {
 			const run = () => {
 				this._pendingCount++;
 
-				Promise.resolve(fn()).then(
+				Promise.resolve((async () => fn())()).then(
```
Comment (wtgtybhertgeghgtwtg) [inline index.js]: Async functions aren't supported in the versions of `node` that `p-queue` supports.  Wanna use `p-try`?
```
pTry(fn).then(
```

Comment (szmarczak) [reply index.js]: That would definitely fix the problem. I did some [benchmarking](https://pastebin.com/raw/K36MZUK2): using promises/async it's about ~10% slower than try/catch (CPU: i7-7700K).
